### PR TITLE
Webworker

### PR DESCRIPTION
**Pull request by SirZach**

### CODE REVIEW

**Comment by SirZach** [comment]
@Createor can you check out https://dev-foosball-pr-61.herokuapp.com/summary make a new game, verify it looks good to you in firebase and all that jazz? it looks good to me but i've changed a lot of files so i'd love to get a second set of eyes on it

**Comment by Createor** [comment]
@SirZach I think there's a problem. The games page returns super slowly with the names all undefined and while a new matchup appears to successfully return "New matchup!" an existing matchup doesn't return anything.
Existing matchup: fooser1 & fooser11 vs fooser14 & fooser9
New matchup: any game involving fooser10, except 10&11 vs 8&9

**Comment by SirZach** [comment]
@Createor we ended up with bad data afterall. the code expects the name to follow the format of "first last" with a space in between to split up the name. in the migration, the names were just "foosballer1"

**Comment by SirZach** [comment]
@Createor it's ready to be tested again

**Comment by Createor** [comment]
Gotcha. Should we allow singly named players, like "Prince"?

**Comment by Createor** [comment]
Or, should we simply move first name and last name to separate keys in the model?

**Comment by SirZach** [comment]
How about a separate issue to break out first and last name?

**Comment by Createor** [comment]
@SirZach Is this the expected comparison? Should it only return the given configuration of teams or is it looking for any arrangement of the players selected?
screenshot at apr 15 10-23-08

**Comment by SirZach** [comment]
oh that's odd and unexpected

**Comment by SirZach** [comment]
@Createor OMG it's the data tricking us AGAIN. what i do for display names is show the first name and the first letter of the last name. the winning team here is actually fooser 14 and fooser 9 but that gets abbreviated to fooser 1 and fooser 9. wow.

**Pull request merged**
