### PR TITLE
Change HipChat Endpoint to Slack

### PR DESCRIPTION
**Pull request by TheConnMan**
The usernames haven't been changed so HipChat usernames will be used until Slack usernames are merged in.

### CODE REVIEW

**Comment by Createor** [comment]
I added a couple slack usernames. I'll add he

**Comment by Createor** [comment]
Wrong button.

I'll add the rest in a bit.

**Comment by TheConnMan** [comment]
Should I go ahead and push the Slack username changes on this branch then we can merge it once you get the rest in?

**Comment by Createor** [comment]
Works for me!

**Comment by SirZach** [comment]
Approve

**Comment by TheConnMan** [comment]
I'll merge as soon as Slack usernames are all added in prod.

**Pull request merged**
